apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    app: nginx
spec:
  containers:
  - name: nginx-container
    image: nginx:1.7.9
    ports:
    - containerPort: 80
  volumeMounts: 
  - name: nginx-vol
    mountPath: /usr/nginx/html